# This file was generated by GoReleaser. DO NOT EDIT.
cask "parraform" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "03a435aa6c6c638b12a5c666b8ce0c48e0be4f3ea0ce73ccc84ed0de124eaf4c"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "581aa97da4e73ea28f4473b4330cf5e858cecbc4d2edd6cc646a59498f6e5ab7"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "28879f097d751adfe46bbdf8c039ed38f2e6335c816bdce08f7ec724a55f6cfb"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2b8c037c8aad2dfca3570e79aca37abb9d4e3ce8e452c77317c67dd77ab939f"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Linux_x86_64.tar.gz"
    end
  end

  name "parraform"
  desc "A transparent terraform wrapper that peeks locks instead of acquiring them at plan time"
  homepage "https://github.com/dev-shimada/parraform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parraform"

  # No zap stanza required
end
