# This file was generated by GoReleaser. DO NOT EDIT.
cask "parraform" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "c6f60a280ff4414cb4b40ebd8ca210756aeba15ca3f044cb7e7efbd92310c800"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "99e9aa06b52474e2064e686b2ad02982c1cea56a08340b9e12ad7a584b71e55e"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fe47b64809796f01882990eec2d52d16692caece7e785a5cf23212871c223f1e"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "25ba432c28859de1c264d8efe6e7ea6547277b8c55caaa46dbffe746e4854610"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Linux_x86_64.tar.gz"
    end
  end

  name "parraform"
  desc "A transparent terraform wrapper that peeks locks instead of acquiring them at plan time"
  homepage "https://github.com/dev-shimada/parraform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parraform"

  # No zap stanza required
end
