# This file was generated by GoReleaser. DO NOT EDIT.
cask "parraform" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7c0602c2796e6bea7236a825f16779ff6632a292c80aa5db8faf283aef6e5f4a"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e5358893750bb5cf6d0e894f35b1aa8118148bf8b04178081997aef019a6abfb"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b0aa2703e1eebbde85d2bdbc4e3a0026553958e5987c5427765b30ae344d784e"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1fe26d7eb191cbe5ae858bbe5d3ed02b6ff08a397928128c108ee83e4051a0e0"
      url "https://github.com/dev-shimada/parraform/releases/download/v#{version}/parraform_Linux_x86_64.tar.gz"
    end
  end

  name "parraform"
  desc "A transparent terraform wrapper that peeks locks instead of acquiring them at plan time"
  homepage "https://github.com/dev-shimada/parraform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "parraform"

  # No zap stanza required
end
